#Enter any DNA sequence
DNA="AGTTGTTAAAGTATGATATTAGCTAGATGCTCTAGGAAAATATACCATGAAGAACTTGCTGTTTTGTAGGATTGATGAAGAAATGCTTTAAAAAGGAATGGTTAGGCTTGGCAGCTGGGCCACTGAAACTGTTTGGTATCAGTATTGCGGTGGAGCTGAGGACTGCAGGGGAATGCGTGCTCCCGTCCTGGTGCAGAAAAAATAAAAGCAGCCAGACAGTAGCTAGATGGTGTTTTGTAACTTTTGGGTTTGGCCCTGATAGTGAACCACTGAATGAAGATGGATGAAGGGAATGCTACTAATGGGGGCCCCAAAGAAAACAAAAATCAGACGTGTGCTCTTCCTGTTTTCTGTCTTTCATTCTTTCCCTGTACTTTGTGCTCAGTACTGTGTTTTGTCAT"

prom1 = DNA.upper()
total = len(prom1)
c = prom1.count("C")
g = prom1.count("G")
gc_total = g+c
gc_prt = gc_total/total*100
print('The% GC content is:', gc_prt,"%")
